[category]

create = """
INSERT INTO categories (id, name, description, is_active, is_deleted, created_at, updated_at)
VALUES (:id, :name, :description, :is_active, FALSE, :created_at, :updated_at)
ON DUPLICATE KEY UPDATE
    is_deleted = FALSE,
    description = VALUES(description),
    is_active = VALUES(is_active),
    updated_at = NOW();
"""

get_all = """
SELECT *
FROM categories
WHERE is_deleted = FALSE
AND is_active = TRUE
ORDER BY created_at DESC;
"""

category_with_subcategories = """
SELECT DISTINCT
    c.id,
    c.name,
    c.description,
    c.is_active,
    c.created_at,
    c.updated_at
FROM categories c

INNER JOIN subcategories s
    ON s.category_id = c.id

INNER JOIN products p
    ON p.subcategory_id = s.id

WHERE
    c.is_deleted = FALSE
    AND c.is_active = TRUE

    AND s.is_deleted = FALSE
    AND s.is_active = TRUE

    AND p.is_deleted = FALSE
    AND p.is_active = TRUE

ORDER BY c.name ASC;
"""

get_by_id = """
SELECT *
FROM categories
WHERE id = :id
AND is_deleted = FALSE;
"""

update = """
UPDATE categories
SET {set_clause},
    updated_at = NOW()
WHERE id = :id
AND is_deleted = FALSE;
"""

# ✅ SOFT DELETE
delete = """
UPDATE categories
SET is_deleted = TRUE,
    updated_at = NOW()
WHERE id = :id
AND is_deleted = FALSE;
"""

activate = """
UPDATE categories
SET is_active = TRUE,
    updated_at = NOW()
WHERE id = :id
AND is_deleted = FALSE;
"""

deactivate = """
UPDATE categories
SET is_active = FALSE,
    updated_at = NOW()
WHERE id = :id
AND is_deleted = FALSE;
"""

restore = """
UPDATE categories
SET is_deleted = FALSE,
    updated_at = NOW()
WHERE id = :id;
"""

# ✅ Admin use only
get_all_with_deleted = """
SELECT *
FROM categories
ORDER BY created_at DESC;
"""


check_subcategories = """
SELECT id FROM subcategories
WHERE category_id = :id
AND is_deleted = FALSE
LIMIT 1;
"""

check_products_by_category = """
SELECT id FROM products
WHERE category_id = :id
AND is_deleted = FALSE
LIMIT 1;
"""