create_token = """
INSERT INTO PasswordReset_Token (user_id, token, expires_at)
VALUES (:user_id, :token, :expires_at)
RETURNING id, user_id, token, expires_at, used, created_at;
"""

get_token = """
SELECT *
FROM PasswordReset_Token
WHERE token = :token;
"""

mark_used = """
UPDATE PasswordReset_Token
SET used = TRUE
WHERE token = :token
RETURNING id;
"""
