[permission]

create_permission = """
INSERT INTO permission (resource_id, action, method, path, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, resource_id, action, method, path, description;
"""

get_all_permissions = """
SELECT id, resource_id, action, description
FROM Permission
ORDER BY id DESC;
"""

delete_permission = """
DELETE FROM Permission
WHERE id = $1
RETURNING id;
"""