[resource]
create_resource = """
INSERT INTO resource (name, description)
VALUES ($1, $2)
RETURNING id, name, description;
"""

get_all_resources = """
SELECT id, name, description
FROM resource
ORDER BY id DESC;
"""

get_resource_by_id = """
SELECT id, name, description
FROM resource
WHERE id = $1;
"""

get_resource_by_name = """
SELECT id, name, description
FROM resource
WHERE name = $1;
"""

update_resource = """
UPDATE resource
SET name = $1,
    description = $2
WHERE id = $3
RETURNING id, name, description;
"""

delete_resource = """
DELETE FROM resource
WHERE id = $1
RETURNING id;
"""