[role]
create_role = """
INSERT INTO role (name, description)
VALUES ($1, $2)
RETURNING id, name, description;
"""

get_all_roles = """
SELECT id, name, description
FROM role
ORDER BY id DESC;
"""

delete_role = """
DELETE FROM role
WHERE id = $1
RETURNING id;
"""