[role_permission]
assign_role_permission = """
INSERT INTO role_permission (role_id, permission_id)
VALUES ($1, $2)
RETURNING role_id, permission_id;
"""

get_permissions_by_role = """
SELECT p.id, p.resource_id, p.action, p.description
FROM role_permission rp
JOIN permission p ON p.id = rp.permission_id
WHERE rp.role_id = $1;
"""

remove_role_permission = """
DELETE FROM role_permission
WHERE role_id = $1 AND permission_id = $2
RETURNING role_id, permission_id;
"""

get_all_role_permissions = """
SELECT r.name AS role, res.name AS resource, p.action
FROM role_permission rp
JOIN role r ON r.id = rp.role_id
JOIN permission p ON p.id = rp.permission_id
JOIN resource res ON res.id = p.resource_id;
"""