[shipping]

create_shipment = """
INSERT INTO shipments (
    id,
    order_id,
    shiprocket_order_id,
    shipment_id,
    awb_code,
    courier_name,
    tracking_url,
    current_status,
    created_at,
    updated_at
) VALUES (
    :id,
    :order_id,
    :shiprocket_order_id,
    :shipment_id,
    :awb_code,
    :courier_name,
    :tracking_url,
    :current_status,
    :created_at,
    :updated_at
);
"""

get_by_awb = """
SELECT *
FROM shipments
WHERE awb_code = :awb_code;
"""

update_status = """
UPDATE shipments
SET current_status = :status,
    updated_at = NOW()
WHERE awb_code = :awb_code;
"""