[subcategory]

# CREATE
create = """
INSERT INTO subcategories (
    id,
    category_id,
    name,
    description,
    images,
    is_active,
    created_at,
    updated_at
) VALUES (
    :id,
    :category_id,
    :name,
    :description,
    :images,
    :is_active,
    :created_at,
    :updated_at
);
"""


get_all = """
SELECT sc.*, c.name AS category_name
FROM subcategories sc
JOIN categories c ON c.id = sc.category_id
WHERE sc.is_deleted = FALSE
ORDER BY sc.created_at DESC;
"""

get_all_minimal = """
SELECT
    sc.id,
    sc.name,
    sc.category_id,
    c.name AS category_name,
    sc.description,
    sc.images,
    sc.is_active
FROM subcategories sc
JOIN categories c
    ON c.id = sc.category_id
WHERE sc.is_deleted = FALSE
ORDER BY sc.created_at DESC;
"""

get_by_id = """
SELECT sc.*, c.name AS category_name
FROM subcategories sc
JOIN categories c ON c.id = sc.category_id
WHERE sc.id = :id;
"""


get_by_category = """
SELECT *
FROM subcategories sc
WHERE sc.category_id = :category_id
  AND sc.is_deleted = FALSE
ORDER BY sc.created_at DESC;
"""


# UPDATE
update = """
UPDATE subcategories
SET {set_clause}, updated_at = NOW()
WHERE id = :id;
"""



delete = """
UPDATE subcategories
SET is_deleted = TRUE,
    updated_at = NOW()
WHERE id = :id
AND is_deleted = FALSE;
"""

activate = """
UPDATE subcategories
SET is_active = TRUE, updated_at = NOW()
WHERE id = :id;
"""


deactivate = """
UPDATE subcategories
SET is_active = FALSE, updated_at = NOW()
WHERE id = :id;
"""

check_products_by_subcategory = """
SELECT id FROM products
WHERE subcategory_id = :id
AND is_deleted = FALSE
LIMIT 1;
"""

get_all_with_products = """
SELECT DISTINCT
    sc.id,
    sc.category_id,
    sc.name,
    sc.description,
    sc.images,
    sc.is_active,
    sc.is_deleted,
    sc.created_at,
    sc.updated_at,
    c.name AS category_name
FROM subcategories sc

INNER JOIN categories c
    ON c.id = sc.category_id

INNER JOIN products p
    ON p.subcategory_id = sc.id

WHERE
    sc.is_deleted = FALSE
    AND sc.is_active = TRUE

    AND c.is_deleted = FALSE
    AND c.is_active = TRUE

    AND p.is_deleted = FALSE
    AND p.is_active = TRUE

ORDER BY sc.created_at DESC;
"""