name: Dev Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Dev Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            set -e

            echo "Connected to DEV server"

            cd /home/ubuntu/cpBackend

            echo "Updating code..."
            git fetch origin
            git checkout dev
            git pull origin dev

            echo "Activating venv..."
            source venv/bin/activate

            echo "Installing dependencies..."
            pip install -r requirements.txt

            echo "Restarting FastAPI..."
            sudo systemctl restart fastapi

            echo "Deployment completed ✅"
