name: test Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print check
        run: |
          if [ -z "${{ secrets.DEV_HOST }}" ]; then
            echo "DEV_HOST missing ❌"
          else
            echo "DEV_HOST exists ✅"
          fi
