name: DEV Auto Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DEV Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ubuntu
          key: ${{ secrets.DEV_SSH_KEY }}
          port: 22
          script: |
            set -e

            echo "Starting DEV Deployment"

            cd /home/ubuntu/cpBackend

            
            git fetch origin
            git checkout dev
            git reset --hard origin/dev

            
            cd citizen

            
            source venv/bin/activate

           
            pip install -r requirements.txt

            
            sudo systemctl restart fastapi

            echo "DEV Deployment Successful"
